[package]
name = "set1"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 3

[dependencies]
arrayref = "0.3.6"
aes = "0.7.5"
base64 = "0.11.0"
cipher = "0.3.0"
hex = "0.4.1"
