[package]
name = "set2"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 3

[dependencies]
aes = "0.7.5"
arrayref = "0.3.6"
base64 = "0.11.0"
cipher = "0.3.0"
rand = "0.7.3"
once_cell = "1.3.1"
