[package]
name = "set2"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 3

[dependencies]
arrayref = "0.3.6"
aes = "0.3.2"
block-cipher-trait = "0.6.2"
base64 = "0.11.0"
